import { useState } from 'react';
import { useAppStore } from '../../hooks/useAppStore';
import { FileText, Download, Send } from 'lucide-react';
import SectionHeader from './SectionHeader';

export default function SitRepGenerator() {
  const { villages, alerts, roads, ndrfTeams } = useAppStore();
  const [isGenerating, setIsGenerating] = useState(false);
  const [sitRepText, setSitRepText] = useState<string | null>(null);

  const veryHighRisk = villages.filter(v => v.riskLevel === 'VERY_HIGH');
  const criticalRoads = roads.filter(r => r.status === 'BLOCKED');
  const activeAlerts = alerts.filter(a => a.status === 'ACTIVE');
  const activeNDRF = ndrfTeams.filter(t => t.status === 'DEPLOYED');

  const generateReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const text = `SITUATION REPORT (SitRep)
Incident: Severe Convective Rainfall / Flash Flood Warning
Date/Time: ${new Date().toLocaleString()}
Jurisdiction: East Khasi Hills District, Meghalaya

1. EXECUTIVE SUMMARY:
A localized cloudburst event is triggering rapid stream rise. High risk of flash flooding and slope failure in the Mawsynram and Sohra blocks.
Current Active Critical Alerts: ${activeAlerts.length}

2. CRITICAL AREAS (VERY HIGH RISK):
${veryHighRisk.map(v => `- ${v.name} (${v.block}): ${v.populationExposure} exposed, ETA ${v.leadTimeMinutes} min.`).join('\n')}

3. INFRASTRUCTURE STATUS:
Roads Blocked: ${criticalRoads.length}
${criticalRoads.map(r => `- ${r.name}: ${r.reason}`).join('\n')}

4. NDRF & RESPONSE DEPLOYMENT:
Active Deployments: ${activeNDRF.length}
${activeNDRF.map(t => `- ${t.name}: Positioned at ${t.currentLocation}`).join('\n')}

5. ACTIONABLE DIRECTIVES:
- Initiate immediate evacuation of ${veryHighRisk[0]?.name || 'impacted'} lowlands.
- Divert traffic from ${criticalRoads[0]?.name || 'affected routes'}.
- Dispatch SitRep to SDMA and NDRF HQ.

Report Generated by: AI-Assisted PRAVAH Ops Engine`;
      
      setSitRepText(text);
      setIsGenerating(false);
    }, 800);
  };

  return (
    <div className="bg-surface-container-lowest rounded border border-outline-variant shadow-sm flex flex-col h-full overflow-hidden">
      <SectionHeader
        icon={<FileText size={18} />}
        title="SitRep Generator"
        badge="AUTO-DRAFT"
      />
      <div className="p-3 flex-1 flex flex-col">
        {sitRepText ? (
          <div className="flex-1 flex flex-col gap-2">
            <textarea 
              readOnly 
              className="flex-1 w-full bg-surface-container-low border border-outline-variant rounded p-2 text-[11px] font-mono text-on-surface resize-none focus:outline-none"
              value={sitRepText}
            />
            <div className="flex items-center gap-2">
              <button className="flex-1 h-8 bg-primary hover:bg-[#1e40af] text-white rounded text-[12px] font-semibold transition-colors flex items-center justify-center gap-1" onClick={() => alert('SitRep Dispatched to SDMA')}>
                <Send size={14} /> Dispatch to SDMA
              </button>
              <button className="h-8 px-3 bg-surface-container-lowest border border-outline-variant hover:bg-surface-container rounded text-[12px] text-on-surface font-semibold flex items-center justify-center gap-1">
                <Download size={14} /> PDF
              </button>
            </div>
          </div>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center gap-3">
            <p className="text-[12px] text-on-surface-variant text-center px-4">
              Auto-generate a standardized Incident Situation Report based on current telemetry, alerts, and NDRF staging.
            </p>
            <button 
              onClick={generateReport}
              disabled={isGenerating}
              className="px-4 h-9 bg-primary hover:bg-[#1e40af] text-white rounded text-[12px] font-semibold transition-colors flex items-center justify-center gap-2"
            >
              {isGenerating ? 'Compiling AI Analysis...' : 'Generate SitRep Draft'}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
